[package]
name = "tic-tac-toe-druid"
version = "0.1.0"
authors = ["joshuawade <wadej@southern.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.7.0"